import "~/styles/globals.css";
import { TopNav } from "~/app/_components/topnav";

import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by loyal subscriber to Theo on Youtube",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" >
      <body className={`${GeistSans.variable} flex flex-col gap-4`}>
        <TopNav />
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
